INSERT INTO artist (name) VALUES ('Travis Scott');         -- artist (1)
INSERT INTO artist (name) VALUES ('Playboi Carti');        -- artist (2)
INSERT INTO artist (name) VALUES ('Skepta');               -- artist (3)
INSERT INTO artist (name) VALUES ('Lil Uzi Vert');         -- artist (4)
INSERT INTO artist (name) VALUES ('Pi''erre Bourne');      -- artist (5)
INSERT INTO artist (name) VALUES ('Nicki Minaj');          -- artist (6)
INSERT INTO artist (name) VALUES ('Bryson Tiller');        -- artist (7)
INSERT INTO artist (name) VALUES ('Chief Keef');           -- artist (8)
INSERT INTO artist (name) VALUES ('Gunna');                -- artist (9)
INSERT INTO artist (name) VALUES ('Red Coldhearted');      -- artist (10)
INSERT INTO artist (name) VALUES ('Young Thug');           -- artist (11)
INSERT INTO artist (name) VALUES ('Young Nudy');           -- artist (12)
INSERT INTO artist (name) VALUES ('KAYTRANADA');           -- artist (13)
INSERT INTO artist (name) VALUES ('Iman Omari');           -- artist (14)
INSERT INTO artist (name) VALUES ('SiR');                  -- artist (15)
INSERT INTO artist (name) VALUES ('Mick Jenkins');         -- artist (16)
INSERT INTO artist (name) VALUES ('Kali Uchis');           -- artist (17)
INSERT INTO artist (name) VALUES ('Masego');               -- artist (18)
INSERT INTO artist (name) VALUES ('VanJess');              -- artist (19)
INSERT INTO artist (name) VALUES ('Estelle');              -- artist (20)
INSERT INTO artist (name) VALUES ('Charlotte Day Wilson'); -- artist (21)
INSERT INTO artist (name) VALUES ('GoldLink');             -- artist (22)
INSERT INTO artist (name) VALUES ('Eight9FLY');            -- artist (23)
INSERT INTO artist (name) VALUES ('Ari PenSmith');         -- artist (24)
INSERT INTO artist (name) VALUES ('Durand Bernarr');       -- artist (25)
INSERT INTO artist (name) VALUES ('Teedra Moses');         -- artist (26)
INSERT INTO artist (name) VALUES ('Tinashe');              -- artist (27)
INSERT INTO artist (name) VALUES ('Pharrell Williams');    -- artist (28)
INSERT INTO artist (name) VALUES ('Baby Keem');            -- artist (29)
INSERT INTO artist (name) VALUES ('21 Savage');            -- artist (30)
INSERT INTO artist (name) VALUES ('Tyler, The Creator');   -- artist (31)
INSERT INTO artist (name) VALUES ('Sam Gellaitry');        -- artist (32)
INSERT INTO artist (name) VALUES ('Fred again..');         -- artist (33)
INSERT INTO artist (name) VALUES ('Swedish House Mafia');  -- artist (34)
INSERT INTO artist (name) VALUES ('Future');               -- artist (35)
INSERT INTO artist (name) VALUES ('Drake');                -- artist (36)
INSERT INTO artist (name) VALUES ('Lil Baby');             -- artist (37)
INSERT INTO artist (name) VALUES ('The Weeknd');           -- artist (38)
INSERT INTO artist (name) VALUES ('Eminem');               -- artist (39)
INSERT INTO artist (name) VALUES ('Taylor Swift');         -- artist (40)

INSERT INTO track (title, duration_ms) VALUES ('STARGAZING', 270000);                 -- track (1)
INSERT INTO track (title, duration_ms) VALUES ('CAROUSEL', 180000);                   -- track (2)
INSERT INTO track (title, duration_ms) VALUES ('SICKO MODE', 312000);                 -- track (3)
INSERT INTO track (title, duration_ms) VALUES ('R.I.P. SCREW', 185000);               -- track (4)
INSERT INTO track (title, duration_ms) VALUES ('STOP TRYING TO BE GOD', 338000);      -- track (5)
INSERT INTO track (title, duration_ms) VALUES ('NO BYSTANDERS', 218000);              -- track (6)
INSERT INTO track (title, duration_ms) VALUES ('SKELETONS', 145000);                  -- track (7)
INSERT INTO track (title, duration_ms) VALUES ('WAKE UP', 145000);                    -- track (8)
INSERT INTO track (title, duration_ms) VALUES ('5% TINT', 196000);                    -- track (9)
INSERT INTO track (title, duration_ms) VALUES ('NC-17', 156000);                      -- track (10)
INSERT INTO track (title, duration_ms) VALUES ('ASTROTHUNDER', 142000);               -- track (11)
INSERT INTO track (title, duration_ms) VALUES ('YOSEMITE', 150000);                   -- track (12)
INSERT INTO track (title, duration_ms) VALUES ('CAN''T SAY', 198000);                 -- track (13)
INSERT INTO track (title, duration_ms) VALUES ('WHO? WHAT!', 198000);                 -- track (14)
INSERT INTO track (title, duration_ms) VALUES ('BUTTERFLY EFFECT', 190000);           -- track (15)
INSERT INTO track (title, duration_ms) VALUES ('HOUSTOUNFORNICATION', 217000);        -- track (16)
INSERT INTO track (title, duration_ms) VALUES ('COFFEE BEAN', 209000);                -- track (17)
INSERT INTO track (title, duration_ms) VALUES ('Long Time (Intro)', 211000);          -- track (18)
INSERT INTO track (title, duration_ms) VALUES ('R.I.P.', 192000);                     -- track (19)
INSERT INTO track (title, duration_ms) VALUES ('Lean 4 Real', 177000);                -- track (20)
INSERT INTO track (title, duration_ms) VALUES ('Old Money', 135000);                  -- track (21)
INSERT INTO track (title, duration_ms) VALUES ('Love Hurts', 180000);                 -- track (22)
INSERT INTO track (title, duration_ms) VALUES ('Shoota', 153000);                     -- track (23)
INSERT INTO track (title, duration_ms) VALUES ('Right Now', 207000);                  -- track (24)
INSERT INTO track (title, duration_ms) VALUES ('Poke It Out', 269000);                -- track (25)
INSERT INTO track (title, duration_ms) VALUES ('Home (KOD)', 162000);                 -- track (26)
INSERT INTO track (title, duration_ms) VALUES ('Fell in Luv', 206000);                -- track (27)
INSERT INTO track (title, duration_ms) VALUES ('Foreign', 142000);                    -- track (28)
INSERT INTO track (title, duration_ms) VALUES ('Pull Up', 216000);                    -- track (29)
INSERT INTO track (title, duration_ms) VALUES ('Mileage', 149000);                    -- track (30)
INSERT INTO track (title, duration_ms) VALUES ('FlatBed Freestyle', 193000);          -- track (31)
INSERT INTO track (title, duration_ms) VALUES ('No Time', 219000);                    -- track (32)
INSERT INTO track (title, duration_ms) VALUES ('Middle of the Summer', 137000);       -- track (33)
INSERT INTO track (title, duration_ms) VALUES ('Choppa Won''t Miss', 217000);         -- track (34)
INSERT INTO track (title, duration_ms) VALUES ('R.I.P. Fredo (Notice Me)', 217000);   -- track (35)
INSERT INTO track (title, duration_ms) VALUES ('Top', 133000);                        -- track (36)
INSERT INTO track (title, duration_ms) VALUES ('DO IT', 132000);                      -- track (37)
INSERT INTO track (title, duration_ms) VALUES ('2 the Music', 235000);                -- track (38)
INSERT INTO track (title, duration_ms) VALUES ('Go DJ', 156000);                      -- track (39)
INSERT INTO track (title, duration_ms) VALUES ('Gray Area', 139000);                  -- track (40)
INSERT INTO track (title, duration_ms) VALUES ('Puff Lah', 113000);                   -- track (41)
INSERT INTO track (title, duration_ms) VALUES ('10%', 186000);                        -- track (42)
INSERT INTO track (title, duration_ms) VALUES ('Need It', 137000);                    -- track (43)
INSERT INTO track (title, duration_ms) VALUES ('Taste', 217000);                      -- track (44)
INSERT INTO track (title, duration_ms) VALUES ('Oh No', 167000);                      -- track (45)
INSERT INTO track (title, duration_ms) VALUES ('What You Need', 183000);              -- track (46)
INSERT INTO track (title, duration_ms) VALUES ('Vex Oh', 162000);                     -- track (47)
INSERT INTO track (title, duration_ms) VALUES ('Scared to Death', 153000);            -- track (48)
INSERT INTO track (title, duration_ms) VALUES ('Freefall', 181000);                   -- track (49)
INSERT INTO track (title, duration_ms) VALUES ('Culture', 248000);                    -- track (50)
INSERT INTO track (title, duration_ms) VALUES ('The Worst in Me', 226000);            -- track (51)
INSERT INTO track (title, duration_ms) VALUES ('September 21', 111000);               -- track (52)
INSERT INTO track (title, duration_ms) VALUES ('Midsection', 289000);                 -- track (53)
INSERT INTO track (title, duration_ms) VALUES ('ORANGE SODA', 129000);                -- track (54)
INSERT INTO track (title, duration_ms) VALUES ('Cash In Cash Out', 216000);           -- track (55)
INSERT INTO track (title, duration_ms) VALUES ('A New Dawn', 216000);                 -- track (56)
INSERT INTO track (title, duration_ms) VALUES ('Duo', 126000);                        -- track (57)
INSERT INTO track (title, duration_ms) VALUES ('Games', 231000);                      -- track (58)
INSERT INTO track (title, duration_ms) VALUES ('Assumptions', 220000);                -- track (59)
INSERT INTO track (title, duration_ms) VALUES ('Turn On The Lights again..', 267000); -- track (60)

INSERT INTO track_artist (track_id, artist_id) VALUES (1, 1);   -- track_artist (1)
INSERT INTO track_artist (track_id, artist_id) VALUES (2, 1);   -- track_artist (2)
INSERT INTO track_artist (track_id, artist_id) VALUES (3, 1);   -- track_artist (3)
INSERT INTO track_artist (track_id, artist_id) VALUES (4, 1);   -- track_artist (4)
INSERT INTO track_artist (track_id, artist_id) VALUES (5, 1);   -- track_artist (5)
INSERT INTO track_artist (track_id, artist_id) VALUES (6, 1);   -- track_artist (6)
INSERT INTO track_artist (track_id, artist_id) VALUES (7, 1);   -- track_artist (7)
INSERT INTO track_artist (track_id, artist_id) VALUES (8, 1);   -- track_artist (8)
INSERT INTO track_artist (track_id, artist_id) VALUES (9, 1);   -- track_artist (9)
INSERT INTO track_artist (track_id, artist_id) VALUES (10, 1);  -- track_artist (10)
INSERT INTO track_artist (track_id, artist_id) VALUES (11, 1);  -- track_artist (11)
INSERT INTO track_artist (track_id, artist_id) VALUES (12, 1);  -- track_artist (12)
INSERT INTO track_artist (track_id, artist_id) VALUES (13, 1);  -- track_artist (13)
INSERT INTO track_artist (track_id, artist_id) VALUES (14, 1);  -- track_artist (14)
INSERT INTO track_artist (track_id, artist_id) VALUES (15, 1);  -- track_artist (15)
INSERT INTO track_artist (track_id, artist_id) VALUES (16, 1);  -- track_artist (16)
INSERT INTO track_artist (track_id, artist_id) VALUES (17, 1);  -- track_artist (17)
INSERT INTO track_artist (track_id, artist_id) VALUES (18, 2);  -- track_artist (18)
INSERT INTO track_artist (track_id, artist_id) VALUES (19, 2);  -- track_artist (19)
INSERT INTO track_artist (track_id, artist_id) VALUES (20, 2);  -- track_artist (20)
INSERT INTO track_artist (track_id, artist_id) VALUES (20, 3);  -- track_artist (21)
INSERT INTO track_artist (track_id, artist_id) VALUES (21, 2);  -- track_artist (22)
INSERT INTO track_artist (track_id, artist_id) VALUES (22, 2);  -- track_artist (23)
INSERT INTO track_artist (track_id, artist_id) VALUES (22, 1);  -- track_artist (24)
INSERT INTO track_artist (track_id, artist_id) VALUES (23, 2);  -- track_artist (25)
INSERT INTO track_artist (track_id, artist_id) VALUES (23, 4);  -- track_artist (26)
INSERT INTO track_artist (track_id, artist_id) VALUES (24, 2);  -- track_artist (27)
INSERT INTO track_artist (track_id, artist_id) VALUES (24, 5);  -- track_artist (28)
INSERT INTO track_artist (track_id, artist_id) VALUES (25, 2);  -- track_artist (29)
INSERT INTO track_artist (track_id, artist_id) VALUES (25, 6);  -- track_artist (30)
INSERT INTO track_artist (track_id, artist_id) VALUES (26, 2);  -- track_artist (31)
INSERT INTO track_artist (track_id, artist_id) VALUES (27, 2);  -- track_artist (32)
INSERT INTO track_artist (track_id, artist_id) VALUES (27, 7);  -- track_artist (33)
INSERT INTO track_artist (track_id, artist_id) VALUES (28, 2);  -- track_artist (34)
INSERT INTO track_artist (track_id, artist_id) VALUES (29, 2);  -- track_artist (35)
INSERT INTO track_artist (track_id, artist_id) VALUES (30, 2);  -- track_artist (36)
INSERT INTO track_artist (track_id, artist_id) VALUES (30, 8);  -- track_artist (37)
INSERT INTO track_artist (track_id, artist_id) VALUES (31, 2);  -- track_artist (38)
INSERT INTO track_artist (track_id, artist_id) VALUES (32, 2);  -- track_artist (39)
INSERT INTO track_artist (track_id, artist_id) VALUES (32, 9);  -- track_artist (40)
INSERT INTO track_artist (track_id, artist_id) VALUES (33, 2);  -- track_artist (41)
INSERT INTO track_artist (track_id, artist_id) VALUES (33, 10); -- track_artist (42)
INSERT INTO track_artist (track_id, artist_id) VALUES (34, 2);  -- track_artist (43)
INSERT INTO track_artist (track_id, artist_id) VALUES (34, 11); -- track_artist (44)
INSERT INTO track_artist (track_id, artist_id) VALUES (35, 2);  -- track_artist (45)
INSERT INTO track_artist (track_id, artist_id) VALUES (35, 12); -- track_artist (46)
INSERT INTO track_artist (track_id, artist_id) VALUES (36, 2);  -- track_artist (47)
INSERT INTO track_artist (track_id, artist_id) VALUES (36, 5);  -- track_artist (48)
INSERT INTO track_artist (track_id, artist_id) VALUES (37, 13); -- track_artist (49)
INSERT INTO track_artist (track_id, artist_id) VALUES (38, 13); -- track_artist (50)
INSERT INTO track_artist (track_id, artist_id) VALUES (38, 14); -- track_artist (51)
INSERT INTO track_artist (track_id, artist_id) VALUES (39, 13); -- track_artist (52)
INSERT INTO track_artist (track_id, artist_id) VALUES (39, 15); -- track_artist (53)
INSERT INTO track_artist (track_id, artist_id) VALUES (40, 13); -- track_artist (54)
INSERT INTO track_artist (track_id, artist_id) VALUES (40, 16); -- track_artist (55)
INSERT INTO track_artist (track_id, artist_id) VALUES (41, 13); -- track_artist (56)
INSERT INTO track_artist (track_id, artist_id) VALUES (42, 13); -- track_artist (57)
INSERT INTO track_artist (track_id, artist_id) VALUES (42, 17); -- track_artist (58)
INSERT INTO track_artist (track_id, artist_id) VALUES (43, 13); -- track_artist (59)
INSERT INTO track_artist (track_id, artist_id) VALUES (43, 18); -- track_artist (60)
INSERT INTO track_artist (track_id, artist_id) VALUES (44, 13); -- track_artist (61)
INSERT INTO track_artist (track_id, artist_id) VALUES (44, 19); -- track_artist (62)
INSERT INTO track_artist (track_id, artist_id) VALUES (45, 13); -- track_artist (63)
INSERT INTO track_artist (track_id, artist_id) VALUES (45, 20); -- track_artist (64)
INSERT INTO track_artist (track_id, artist_id) VALUES (46, 13); -- track_artist (65)
INSERT INTO track_artist (track_id, artist_id) VALUES (46, 21); -- track_artist (66)
INSERT INTO track_artist (track_id, artist_id) VALUES (47, 13); -- track_artist (67)
INSERT INTO track_artist (track_id, artist_id) VALUES (47, 22); -- track_artist (68)
INSERT INTO track_artist (track_id, artist_id) VALUES (47, 23); -- track_artist (69)
INSERT INTO track_artist (track_id, artist_id) VALUES (47, 24); -- track_artist (70)
INSERT INTO track_artist (track_id, artist_id) VALUES (48, 13); -- track_artist (71)
INSERT INTO track_artist (track_id, artist_id) VALUES (49, 13); -- track_artist (72)
INSERT INTO track_artist (track_id, artist_id) VALUES (49, 25); -- track_artist (73)
INSERT INTO track_artist (track_id, artist_id) VALUES (50, 13); -- track_artist (74)
INSERT INTO track_artist (track_id, artist_id) VALUES (50, 26); -- track_artist (75)
INSERT INTO track_artist (track_id, artist_id) VALUES (51, 13); -- track_artist (76)
INSERT INTO track_artist (track_id, artist_id) VALUES (51, 27); -- track_artist (77)
INSERT INTO track_artist (track_id, artist_id) VALUES (52, 13); -- track_artist (78)
INSERT INTO track_artist (track_id, artist_id) VALUES (53, 13); -- track_artist (79)
INSERT INTO track_artist (track_id, artist_id) VALUES (53, 28); -- track_artist (80)
INSERT INTO track_artist (track_id, artist_id) VALUES (54, 29); -- track_artist (81)
INSERT INTO track_artist (track_id, artist_id) VALUES (55, 28); -- track_artist (82)
INSERT INTO track_artist (track_id, artist_id) VALUES (55, 30); -- track_artist (83)
INSERT INTO track_artist (track_id, artist_id) VALUES (55, 31); -- track_artist (84)
INSERT INTO track_artist (track_id, artist_id) VALUES (56, 32); -- track_artist (85)
INSERT INTO track_artist (track_id, artist_id) VALUES (57, 32); -- track_artist (86)
INSERT INTO track_artist (track_id, artist_id) VALUES (58, 32); -- track_artist (87)
INSERT INTO track_artist (track_id, artist_id) VALUES (59, 32); -- track_artist (88)
INSERT INTO track_artist (track_id, artist_id) VALUES (60, 33); -- track_artist (89)
INSERT INTO track_artist (track_id, artist_id) VALUES (60, 34); -- track_artist (90)
INSERT INTO track_artist (track_id, artist_id) VALUES (60, 35); -- track_artist (91)

INSERT INTO release (title, type, year) VALUES ('ASTROWORLD', 'Album', 2018);                  -- release (1)
INSERT INTO release (title, type, year) VALUES ('Die Lit', 'Album', 2018);                     -- release (2)
INSERT INTO release (title, type, year) VALUES ('BUBBA', 'Album', 2019);                       -- release (3)
INSERT INTO release (title, type, year) VALUES ('ORANGE SODA', 'Single', 2019);                -- release (4)
INSERT INTO release (title, type, year) VALUES ('Cash In Cash Out', 'Single', 2022);           -- release (5)
INSERT INTO release (title, type, year) VALUES ('IV', 'EP', 2021);                             -- release (6)
INSERT INTO release (title, type, year) VALUES ('Turn On The Lights again..', 'Single', 2022); -- release (7)

INSERT INTO genre (name) VALUES ('Hip-hop');     -- genre (1)
INSERT INTO genre (name) VALUES ('Rap');         -- genre (2)
INSERT INTO genre (name) VALUES ('Electronic');  -- genre (3)
INSERT INTO genre (name) VALUES ('Techno');      -- genre (4)
INSERT INTO genre (name) VALUES ('Trap');        -- genre (5)
INSERT INTO genre (name) VALUES ('Dubstep');     -- genre (6)
INSERT INTO genre (name) VALUES ('Jazz');        -- genre (7)
INSERT INTO genre (name) VALUES ('Rock');        -- genre (8)
INSERT INTO genre (name) VALUES ('Blues');       -- genre (9)
INSERT INTO genre (name) VALUES ('Indie');       -- genre (10)
INSERT INTO genre (name) VALUES ('Alternative'); -- genre (11)
INSERT INTO genre (name) VALUES ('Samba');       -- genre (12)
INSERT INTO genre (name) VALUES ('Funk');        -- genre (13)
INSERT INTO genre (name) VALUES ('Disco');       -- genre (14)
INSERT INTO genre (name) VALUES ('Grunge');      -- genre (15)

INSERT INTO release_genre (release_id, genre_id) VALUES (1, 1); -- release_genre (1)
INSERT INTO release_genre (release_id, genre_id) VALUES (1, 2); -- release_genre (2)
INSERT INTO release_genre (release_id, genre_id) VALUES (2, 1); -- release_genre (3)
INSERT INTO release_genre (release_id, genre_id) VALUES (2, 2); -- release_genre (4)
INSERT INTO release_genre (release_id, genre_id) VALUES (3, 3); -- release_genre (5)
INSERT INTO release_genre (release_id, genre_id) VALUES (4, 1); -- release_genre (6)
INSERT INTO release_genre (release_id, genre_id) VALUES (5, 1); -- release_genre (7)
INSERT INTO release_genre (release_id, genre_id) VALUES (5, 2); -- release_genre (8)
INSERT INTO release_genre (release_id, genre_id) VALUES (6, 3); -- release_genre (9)
INSERT INTO release_genre (release_id, genre_id) VALUES (7, 3); -- release_genre (10)

INSERT INTO release_artist (release_id, artist_id) VALUES (1, 1);  -- release_artist (1)
INSERT INTO release_artist (release_id, artist_id) VALUES (2, 2);  -- release_artist (2)
INSERT INTO release_artist (release_id, artist_id) VALUES (3, 13); -- release_artist (3)
INSERT INTO release_artist (release_id, artist_id) VALUES (4, 29); -- release_artist (4)
INSERT INTO release_artist (release_id, artist_id) VALUES (5, 28); -- release_artist (5)
INSERT INTO release_artist (release_id, artist_id) VALUES (5, 30); -- release_artist (6)
INSERT INTO release_artist (release_id, artist_id) VALUES (5, 31); -- release_artist (7)
INSERT INTO release_artist (release_id, artist_id) VALUES (6, 32); -- release_artist (8)
INSERT INTO release_artist (release_id, artist_id) VALUES (7, 33); -- release_artist (9)
INSERT INTO release_artist (release_id, artist_id) VALUES (7, 34); -- release_artist (10)

INSERT INTO release_track (release_id, track_id, track_number) VALUES (1, 1, 1);   -- release_track (1)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (1, 2, 2);   -- release_track (2)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (1, 3, 3);   -- release_track (3)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (1, 4, 4);   -- release_track (4)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (1, 5, 5);   -- release_track (5)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (1, 6, 6);   -- release_track (6)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (1, 7, 7);   -- release_track (7)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (1, 8, 8);   -- release_track (8)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (1, 9, 9);   -- release_track (9)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (1, 10, 10); -- release_track (10)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (1, 11, 11); -- release_track (11)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (1, 12, 12); -- release_track (12)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (1, 13, 13); -- release_track (13)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (1, 14, 14); -- release_track (14)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (1, 15, 15); -- release_track (15)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (1, 16, 16); -- release_track (16)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (1, 17, 17); -- release_track (17)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (2, 18, 1);  -- release_track (18)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (2, 19, 2);  -- release_track (19)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (2, 20, 3);  -- release_track (20)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (2, 21, 4);  -- release_track (21)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (2, 22, 5);  -- release_track (22)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (2, 23, 6);  -- release_track (23)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (2, 24, 7);  -- release_track (24)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (2, 25, 8);  -- release_track (25)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (2, 26, 9);  -- release_track (26)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (2, 27, 10); -- release_track (27)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (2, 28, 11); -- release_track (28)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (2, 29, 12); -- release_track (29)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (2, 30, 13); -- release_track (30)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (2, 31, 14); -- release_track (31)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (2, 32, 15); -- release_track (32)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (2, 33, 16); -- release_track (33)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (2, 34, 17); -- release_track (34)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (2, 35, 18); -- release_track (35)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (2, 36, 19); -- release_track (36)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (3, 37, 1);  -- release_track (37)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (3, 38, 2);  -- release_track (38)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (3, 39, 3);  -- release_track (39)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (3, 40, 4);  -- release_track (40)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (3, 41, 5);  -- release_track (41)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (3, 42, 6);  -- release_track (42)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (3, 43, 7);  -- release_track (43)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (3, 44, 8);  -- release_track (44)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (3, 45, 9);  -- release_track (45)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (3, 46, 10); -- release_track (46)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (3, 47, 11); -- release_track (47)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (3, 48, 12); -- release_track (48)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (3, 49, 13); -- release_track (49)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (3, 50, 14); -- release_track (50)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (3, 51, 15); -- release_track (51)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (3, 52, 16); -- release_track (52)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (3, 53, 17); -- release_track (53)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (4, 54, 1);  -- release_track (54)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (5, 55, 1);  -- release_track (55)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (6, 56, 1);  -- release_track (56)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (6, 57, 2);  -- release_track (57)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (6, 58, 3);  -- release_track (58)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (6, 59, 4);  -- release_track (59)
INSERT INTO release_track (release_id, track_id, track_number) VALUES (7, 60, 1);  -- release_track (60)
