version: '3.9'

services:
  mysic-db:
    container_name: mysic_db
    image: postgres:latest
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DATABASE: 'mysic_db'
    ports:
      - '5432:5432'
    volumes:
      - ./.docker/data:/var/lib/postgresql/data
    networks:
      - mysic-db-network

  mysic-db-admin:
    container_name: mysic_db_admin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    networks:
      - mysic-db-network
    depends_on:
      - mysic-db

networks:
  mysic-db-network:
    name: mysic_db_network
    driver: bridge
